# Generated by Django 5.1.3 on 2024-12-03 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fashion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fashion',
            name='joined_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='fashion',
            name='phone',
            field=models.IntegerField(null=True),
        ),
    ]
